### ISSUE TITLE
Verify Czech translation for the conv.dev section

### ISSUE THREAD

**Issue by chrislo27** [chrislo27/Stray-core#3]
Please check (and edit) if the Czech translation of conv.dev0-4 is accurate, I used Google Translate to attempt to at least get something there.

Namely these:

```
conv.dev0=Vítejte.
conv.dev1=To je brzy kopie hry.
conv.dev2=Očekávejte nedokončený obsah.
conv.dev3=To znamená, aby se první pohled hry.
conv.dev4=Užijte si to!
```

English version:

```
conv.dev0=Welcome.
conv.dev1=This is an early development version of the game.
conv.dev2=Expect unfinished content and possibly bugs.
conv.dev3=This is meant to give you a rough idea of the game.
conv.dev4=Enjoy!
```

**Comment by chrislo27** [comment]
Everything past dev0 is broken.

**Comment by matt-lebl** [comment]
Sure. I'll actually work on this now, I promise. I just need to go get my passport picture taken.

**Comment by chrislo27** [comment]
Six days have passed since the passporting.

I'm not rushing you, but just remember. This is NOT in any way high priority, localization is more of a after v1.0 thing.

**Comment by chrislo27** [comment]
You're fired for not translating.

You can be re-hired as an intern.
